//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcRaviDashApp.DB_Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpChetu
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public string Eemail { get; set; }
        public string City { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
